[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Underscores = "d9a01c3f-67ce-4d8c-9b55-35f6e4050bb1"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
